// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUdUvwvF0hdEIwweOEpR45kBQR4k3cCDM',
    appId: '1:841031657296:web:5ec69d8ede6288c0262e55',
    messagingSenderId: '841031657296',
    projectId: 'smart-operator-56cf4',
    authDomain: 'smart-operator-56cf4.firebaseapp.com',
    storageBucket: 'smart-operator-56cf4.firebasestorage.app',
    measurementId: 'G-65JNTRBHHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi08p3DM4dALLdk6fsRoPhj-xAAYvEGVU',
    appId: '1:841031657296:android:6d7cb0764316bf50262e55',
    messagingSenderId: '841031657296',
    projectId: 'smart-operator-56cf4',
    storageBucket: 'smart-operator-56cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj12A974IsnH1QwgnVnqewUFySqVVW4S8',
    appId: '1:841031657296:ios:d5f22f9c2974ae64262e55',
    messagingSenderId: '841031657296',
    projectId: 'smart-operator-56cf4',
    storageBucket: 'smart-operator-56cf4.firebasestorage.app',
    iosBundleId: 'com.smartoperator.smartOperatorAssistant',
  );
}
